# Generated by Django 4.2.5 on 2023-11-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="item",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=4)),
                ("team", models.CharField(max_length=4)),
                ("status", models.CharField(max_length=2)),
                ("register_date", models.DateField()),
                ("rental_date", models.DateField()),
                ("return_date", models.DateField()),
            ],
        ),
    ]
